name: Send Changelog to Discord

on:
  push:
    branches: [ "main", "master" ]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Send custom message to Discord
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          Update in Aetheria RPG Core!
          
          Latest commit:
          `${{ github.event.head_commit.message }}`
          
          View full [CHANGELOG.md](https://github.com/developerjuzo/AetheriaRPGcore/blob/main/CHANGELOG.md) for details!
